server:
  port: 8282

spring:
  datasource:
  ##主数据源
    druid:
      master: 
        jdbc-url: jdbc:mysql://172.28.13.138:3306/yf_selenium?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: Za&bbix13
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      ## 其它数据源-sqlserver
      sqlserver:
        jdbc-url: jdbc:sqlserver://172.28.13.140;DatabaseName=yfim_sit
        username: SA
        password: China1234
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      ## 其他数据源-oracle  
      oracle:
        url: jdbc:oracle:thin:@//localhost:1521/db0
        username: admin
        password: admin
        driver-class-name: oracle.jdbc.driver.OracleDriver
    
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 1
      # 最小连接池数量
      minIdle: 1
      # 最大连接池数量
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 验证连接有效与否的SQL，不同的数据配置不同
      validationQuery: select 1
      # 建议配置为true，不影响性能，并且保证安全性。
      # 申请连接的时候检测，如果空闲时间大于
      # timeBetweenEvictionRunsMillis，
      # 执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      # 这里建议配置为TRUE，防止取到的连接不可用
      testOnBorrow: true
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      # 是否缓存preparedStatement，也就是PSCache。
      # PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      # 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
      # 作者在5.5版本中使用PSCache，通过监控界面发现PSCache有缓存命中率记录，
      # 该应该是支持PSCache。
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 属性类型是字符串，通过别名的方式配置扩展插件，
      # 常用的插件有：
      # 监控统计用的filter:stat
      # 日志用的filter:log4j
      # 防御sql注入的filter:wall
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: durid
        
  ################# 配置 elasticsearch ##################
  ## elasticsearch 配置默认为127.0.0.1:9200 ,修改es健康检查地址
  elasticsearch:
    rest:
      uris: ["http://172.28.13.140:9200"]
  data:    elasticsearch:
      repositories:        enabled: true      cluster-nodes: 172.28.13.140:9300
      cluster-name: my-es 
 ############### 配置 redis #############################
  # 单机版  redis:
    ## 默认数据库（0）    database: 0
    ## 服务器地址
    host: 172.28.13.140
    ## 密码
    password: China1234
    ## 端口号
    port: 6379
    ## 连接超时时间（毫秒），默认2000ms
    timeout: 10000
    jedis:      pool:
        ## 连接池最大连接数，负值表示没有限制        max-active: 200
        ## 连接池最大阻塞等待时间（毫秒），负值表示没有限制
        max-wait: 60000
        ## 连接池中最大空闲连接
        max-idle: 2
        ## 连接池中最小空闲连接
        min-idle: 0
        




# mybatis-plus:#  mapper-locations: classpath*:com/redmaple/**/dao/*.xml
#  







        
